### ISSUE TITLE
Transition plan tasks

### ISSUE THREAD

**Issue by rplzzz** [claudiatebaldi/hectorcal#33]
- [x] Find where metrosamp tuning parameters for Protocol 48 are recorded.
- [x] Document termination criteria.
- [x] Document use of multiple Markov chains for each protocol.
- [x] Document procedure for concatenating original batch and continuation batch runs into a single dataset that can be used in the analysis functions.
- [x] Document workflow for running the MCMC runs.
- [x] Archive the old MCMC output data.
- [x] Determine whether any of the material on the `pkg-data-update` branch is still needed.  
    * I originally created this branch when I thought the PCA code was going to have to be updated to work with the new data.  It's not clear that anything on it is still required.
    * _Update_: I don't see anything in the branch that we still need.  I'll leve the branch in place in case there is something I missed, but I expect you won't ever have cause to look at it.

**Comment by rplzzz** [comment]
The MCMC procedure is described in detail in the aptly titled "Monte Carlo Procedure" subsection.
On the subject of termination criteria, we say that we ran the MCMC until the Gelman-Rubin statistic (Rhat) was <= 1.1.  We also note that for this protocol that happened in the initial batch.

**Comment by rplzzz** [comment]
The initial guess and tuned proposal distribution parameters for the MCMC are set automatically in the `mc_run_conc` and `mc_run_emiss` functions.  The initial guess is the same for all protocols, while the scale factors are protocol dependent.

Here is the logic for the concentration-driven case:
https://github.com/kdorheim/hectorcal/blob/a9d49d04c66b9b225d1b4140555f4da4a344edfc/inst/scripts/mc-runs-conc.R#L76-L154
The basic parameters set on line 84 are what is used in Protocol 48, which is the focus of the paper.  It is possible to override these defaults by restarting from a saved output file with different values saved in it, but we didn't do that in any of the production runs.

You can also find this information after the fact by looking at the `metrosamp` object output from the calculation.
```
> mcrc48 <- readRDS('analysis/paper2/mcmc-output/conc/hectorcal-25000-48-mcrslt.rds')
> str(mcrc48)
List of 5
 $ samples: num [1:25000, 1:4] 3 3 3 3 2.63 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : NULL
  .. ..$ : chr [1:4] "S" "diff" "alpha" "volscl"
 $ samplp : num [1:25000] -23.1 -23.1 -23.1 -23.1 -23 ...
 $ accept : num 0.21
 $ plast  : Named num [1:4] 2.524 3.941 0.501 1.231
  ..- attr(*, "names")= chr [1:4] "S" "diff" "alpha" "volscl"
 $ scale  : Named num [1:4] 0.75 1.25 0.5 0.5
  ..- attr(*, "names")= chr [1:4] "S" "diff" "alpha" "volscl"
 - attr(*, "class")= chr [1:2] "metrosamp" "list"
> mcrc48$scale
     S   diff  alpha volscl 
  0.75   1.25   0.50   0.50 
```

**Comment by rplzzz** [comment]
It turns out the old MCMC output, at least for the concentration-driven runs, is included in the repository, in `analysis/paper2/mcmc-output/conc`.  I don't see a corresponding directory of emissions-driven runs, however.

**Comment by rplzzz** [comment]
How to run the MCMC runs on PIC is described in `inst/scripts/readme.md`.

**Comment by rplzzz** [comment]
Results from MCMC runs are read in using the `proc_mc_rslts` function.  It takes a whole directory of output files and produces a list of three elements:
* `runstats`: For each protocol, a list of summary statistics for that protocol's runs (recall that there are 16 independent Markov chains for each protocol -- these statistics apply to the collection).  The statistics calculated are:
    * `accept`: The fraction of all proposal steps that were accepted.
    * `neff`: The number of effective samples, after accounting for autocorrelation.  There will be a value for each parameter.
    * `rhat`: The Gelman-Rubin statistic (called the "potential scale reduction factor" in the formatted output).  There will be a value and confidence interval for each model parameter, plus an overall value called the "multivariate psrf".
* `mcobjs`: The `metrosamp` objects generated by the MCMC runs.  These are indexed by protocol.  Within each protocol there is a list of `metrosamp` objects indexed by the name of the file they were read from.  Each of these is one of the 16 independent Markov chains that was run for that protocol.  E.g.:
```
> names(mcruns_conc$mcobjs$`48`)
 [1] "analysis/mcmc/conc/primary/hectorcal-conc-100000-48-mcrslt.rds"
 [2] "analysis/mcmc/conc/primary/hectorcal-conc-100000-49-mcrslt.rds"
 [3] "analysis/mcmc/conc/primary/hectorcal-conc-100000-50-mcrslt.rds"
 ...
[16] "analysis/mcmc/conc/primary/hectorcal-conc-100000-63-mcrslt.rds"
```
* `codaobjs`: `mcmc.list` objects from the `CODA` package.  These contain the same information as the `mcobjs`; they're just reformatted to be used with some of the analysis functions in `CODA`.

(have to run -- to be continued...)

**Comment by rplzzz** [comment]
## Run ID numbers and multiple Markov chains
Each run has an ID number from 0-127 (or from 128-255, which produces the same runs, but with extra debugging output).  The meaning of the the run ID is explained in the documentation to `encode_runid` and `decode_runid`.  Briefly, the first four bits in the binary representation of the run ID serve as flags that turn on or off various features of the calibration protocol.  Thus, run 48 (b00110000) has the first two flags (debug and mean calibration) cleared, and the second two (PCA and heat flux) set.  

The last four bits don't affect the calibration protocol.  Instead, they allow us to run multiple independent Markov chains for each protocol by providing a serial number for each chain.  This serial number is used to select a different random number seed for each chain, which produces an independent chain.  So, for each protocol, there will be 16 runs that all provide results for that protocol.  The protocol itself is named for the lowest run ID that implements that protocol.  For example, run IDs 48-63 all implement the same protocol, which we refer to as Protocol 48.  The `proc_mc_rslts` function reads all of the runs in a directory and groups them by protocol for analysis.

**Comment by rplzzz** [comment]
@kdorheim I believe this covers everything we talked about.  Please let me know if there is anything I missed.

**Comment by kdorheim** [comment]
@rplzzz thanks this was very helpful and I am pretty sure covers more than we discussed last week.

**Comment by kdorheim** [comment]
@claudiatebaldi Robert documented the MCMC code here and the data lives on pic at `/pic/projects/GCAM/rpl/hectorcal-output-archive.tgz`. If you have any questions please let me know. If you are unable to access the `/pic/projects/GCAM/rpl` directory, email pic support and they will be able to give you access.

**Comment by claudiatebaldi** [comment]
Perfect, thank you!
